import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Button } from 'antd-mobile';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src="/images/profile.jpg" alt="커피공장" width={400} height={400} />
        <div className="App">
          <Link href="/gift">
            <Button type="primary">커피공장</Button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
